### ISSUE TITLE
Bug - Infinite loading

### ISSUE THREAD

**Issue by rsholokh** [Leirach/fate-save-editor#1]
Doesn't work - **infinite loading** when uploaded a file or chosen the LOAD AN EMPTY FILE option. Both remote on [fate-save-editor.onrender.com](https://fate-save-editor.onrender.com) and local.
![fate-save-editor-issue](https://user-images.githubusercontent.com/67190621/205486397-f73c877d-8f15-4004-80d8-e71a2b77dbb4.png)

**Comment by Leirach** [comment]
I'll check it out, thanks for pointing it out

**Comment by rsholokh** [comment]
Works
